version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: monitoring_db_shared
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5435:5432"  # Puerto diferente para evitar conflictos
    volumes:
      - postgres_data_shared:/var/lib/postgresql/data
      - ./apiNodeJS/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - monitoring-network

  api-nodejs:
    build: ./apiNodeJS
    container_name: monitoring_api_nodejs
    environment:
      - NODE_ENV=production
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=monitoring
      - PORT=7000
      - JSON_FILE_PATH=/app/data/monitoring_data.json
    ports:
      - "7000:7000"
    volumes:
      - ./apiNodeJS/data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - monitoring-network

  api-python:
    build: ./apiPython
    container_name: monitoring_api_python
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=monitoring
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./apiPython/data:/app/data
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - monitoring-network

volumes:
  postgres_data_shared:

networks:
  monitoring-network:
    driver: bridge