version: '3.8'

services:
  # Backend Go
  backend:
    image: pablo03r/backend-go-fase2:latest
    container_name: monitor-agent-backend
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s