# Usamos una imagen base de Go para construir la aplicación
FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY main.go .

RUN go mod init monitor-agent && \
    go mod tidy && \
    CGO_ENABLED=0 GOOS=linux go build -o monitor-agent .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN mkdir -p /proc

COPY --from=builder /app/monitor-agent /monitor-agent

EXPOSE 8080

CMD ["/monitor-agent"]