version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: monitoring_db_nodejs
    environment:
      POSTGRES_DB: monitoring
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"  # Puerto diferente para evitar conflictos
    volumes:
      - postgres_data_nodejs:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - monitoring-network

  api-nodejs:
    build: .
    container_name: monitoring_api_nodejs
    environment:
      - NODE_ENV=production
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=monitoring
      - PORT=7000
      - JSON_FILE_PATH=/app/data/monitoring_data.json
    ports:
      - "7000:7000"
    volumes:
      - ./data:/app/data  # Para el archivo JSON
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - monitoring-network

volumes:
  postgres_data_nodejs:

networks:
  monitoring-network:
    driver: bridge